### ISSUE TITLE
无法使用本地的ts视频吗

### ISSUE THREAD

**Issue by lichq5** [kinglisky/silent-film#3]
我在data中引用本地的ts视频时会导入：
data() {
    return {
       url: "url(" + require("../assets/test.ts") + ")" 
   }
}
Module parse failed: Unexpected character '@' (1:1)
File was processed with these loaders:
 * ./node_modules/eslint-loader/index.js
You may need an additional loader to handle the result of these loaders.
(Source code omitted for this binary file)
但我在导入其他格式的视频时可以

**Comment by kinglisky** [comment]
> 我在data中引用本地的ts视频时会导入：
> data() {
> return {
> url: "url(" + require("../assets/test.ts") + ")"
> }
> }
> Module parse failed: Unexpected character '@' (1:1)
> File was processed with these loaders:
> 
> * ./node_modules/eslint-loader/index.js
>   You may need an additional loader to handle the result of these loaders.
>   (Source code omitted for this binary file)
>   但我在导入其他格式的视频时可以

> You may need an additional loader to handle the result of these loaders.

看起来是需要配置对应的 loader，本地的视频可以试试 `http://localhost:1234/assets/test.ts` 这样的资源地址。
