### ISSUE TITLE
包下载后在引入的时候直接报错了

### ISSUE THREAD

**Issue by 1807826635** [kinglisky/silent-film#4]
Critical dependency: the request of a dependency is an expression

**Comment by kinglisky** [comment]
> Critical dependency: the request of a dependency is an expression

使用方式麻烦贴下，完整的报错发我下

**Comment by 1807826635** [comment]
解决的 重装了依赖 但是现在的问题是什么样的ts文件才能播放 设计给我的MP4 我再网上转成了ts 放到阿里的oss上 就变成了一堆的雪花 但是示例给的可以播 请问 对于视频有什么要求呢

**Comment by 1807826635** [comment]
![Uploading image.png…]()

**Comment by 1807826635** [comment]
加载的时候的有一个白色的过程 能解决吗 比如先隐藏什么的

**Comment by 1807826635** [comment]
warning  in ./node_modules/silent-film-player/lib/index.js

1:263-264 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

 warning  in ./node_modules/silent-film-player/lib/wasm-binary.js

1:263-264 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

 warning  in ./node_modules/silent-film-player/lib/index.js

1:292-296 Critical dependency: the request of a dependency is an expression

 warning  in ./node_modules/silent-film-player/lib/wasm-binary.js

1:292-296 Critical dependency: the request of a dependency is an expression

控制台有四个警告 可以不用管吗
