### ISSUE TITLE
加载的时候有个白色的过程

### ISSUE THREAD

**Issue by 1807826635** [kinglisky/silent-film#5]
加载的时候有个白色的过程 能隐藏吗 
poster 这个配置好像没有作用

**Comment by kinglisky** [comment]
> 加载的时候有个白色的过程 能隐藏吗
> poster 这个配置好像没有作用

你可以在 canvas 自己加一个遮罩层，在视频资源没开始播放前展示，视频开始播放后移除这个遮罩。
